## Travis CI configuration for the serial-core library.
##
##   <https://travis-ci.org/mdklatt/serial-python>
##
language: python

python:
  - "3.6"

branches:
  only:
    - master
    - dev

sudo: false

install:
  - python -m pip install . -r test/requirements.txt

script:
  - pytest --verbose test/
