## Travis CI configuration for the serial-core library.
##
##   <https://travis-ci.org/mdklatt/serial-python>
##
language: python

python:
  - "2.7"

branches:
  only:
    - py27

sudo: false

install:
  - pip install . -r test/requirements.txt

script:
  - pytest --verbose test/
