# Travis CI configuration for the serial-core Python library.

sudo: false

language: python
python:
  - "2.6"
  - "2.7"

branches:
  only:
    - master
    - dev

install: python setup.py install

script: py.test test/
