## Travis CI configuration for the serial-core library.
##
## This verifies that the library can be installed and pass its test suite.
##
language: python
python:
  - "2.6"
  - "2.7"

branches:
  only:
    - master
    - dev

sudo: false

install:
  - python setup.py install

before_script:
  # Travis CI preinstalls py.test, but automatic test discovery fails for the
  # default version (2.6), so make sure the correct version is installed.
  - pip install --requirement=requirements-test.txt

script:
  - py.test --verbose test/
