# Travis CI configuration for the serial-core Python library.

language: python
python:
    - "2.6"
    - "2.7"

branches:
    only:
        - master
        - dev

install:
    - pip install -r requirements-py26.txt

script: python test/run_tests.py
