## Travis CI configuration for the serial-core library.
##
##   <https://travis-ci.org/mdklatt/serial-python>
##
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

branches:
  only:
    - master
    - dev

dist: xenial 

install:
  - python -m pip install pipenv
  - pipenv install --dev
  - pipenv run pip install -e .

script:
  - pipenv run pytest --verbose test/
