## Travis CI configuration for the serial-core library.
##
##  <https://travis-ci.org/mdklatt/serial-python>
##
language: python

python:
  - "2.7"

branches:
  only:
    - master
    - dev

sudo: false

install:
  - pip install . -r requirements-test.txt

script:
  - py.test --verbose test/
